# Generated by Django 4.2.9 on 2026-01-09 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "target_role",
                    models.CharField(
                        choices=[("all", "全部"), ("family", "亲属"), ("staff", "工作人员")],
                        default="all",
                        max_length=20,
                        verbose_name="目标受众",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "已发布"),
                            ("draft", "草稿"),
                            ("retracted", "已撤回"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "expire_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告管理",
                "ordering": ["-publish_time"],
            },
        ),
    ]
