# Generated by Django 4.2.9 on 2026-01-19 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("announcements", "0002_announcementreadstatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-publish_time"],
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="expire_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expire Time"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="publish_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Publish Time"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("retracted", "Retracted"),
                ],
                default="published",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="target_role",
            field=models.CharField(
                choices=[("all", "All"), ("family", "Family"), ("staff", "Staff")],
                default="all",
                max_length=20,
                verbose_name="Target Audience",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.DeleteModel(
            name="AnnouncementReadStatus",
        ),
    ]
