# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("patients", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.familyuser",
                verbose_name="支付人",
            ),
        ),
        migrations.AddField(
            model_name="billitem",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.bill",
                verbose_name="账单",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.familyuser",
                verbose_name="关联亲属",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="院民",
            ),
        ),
    ]
