# Generated by Django 4.2.9 on 2026-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("alipay", "支付宝"),
                    ("wechat", "微信支付"),
                    ("bank", "银行转账"),
                    ("cash", "现金"),
                    ("balance", "余额支付"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
    ]
