# Generated by Django 4.2.9 on 2026-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        help_text="房间号，例如：101、102、201等",
                        max_length=20,
                        unique=True,
                        verbose_name="房间号",
                    ),
                ),
                (
                    "bed1_id",
                    models.CharField(
                        blank=True,
                        help_text="房间内第一个床位的ID",
                        max_length=20,
                        null=True,
                        verbose_name="床位1 ID",
                    ),
                ),
                (
                    "bed2_id",
                    models.CharField(
                        blank=True,
                        help_text="房间内第二个床位的ID",
                        max_length=20,
                        null=True,
                        verbose_name="床位2 ID",
                    ),
                ),
                (
                    "bed3_id",
                    models.CharField(
                        blank=True,
                        help_text="房间内第三个床位的ID",
                        max_length=20,
                        null=True,
                        verbose_name="床位3 ID",
                    ),
                ),
                (
                    "bed4_id",
                    models.CharField(
                        blank=True,
                        help_text="房间内第四个床位的ID",
                        max_length=20,
                        null=True,
                        verbose_name="床位4 ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "房间信息",
                "verbose_name_plural": "房间信息",
                "db_table": "rooms",
            },
        ),
    ]
