# Generated by Django 4.2.9 on 2026-01-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room Info", "verbose_name_plural": "Room Info"},
        ),
        migrations.RemoveField(
            model_name="room",
            name="bed1_id",
        ),
        migrations.RemoveField(
            model_name="room",
            name="bed2_id",
        ),
        migrations.RemoveField(
            model_name="room",
            name="bed3_id",
        ),
        migrations.RemoveField(
            model_name="room",
            name="bed4_id",
        ),
        migrations.AddField(
            model_name="room",
            name="bed1",
            field=models.CharField(
                blank=True,
                help_text="Bed 1 ID",
                max_length=20,
                null=True,
                verbose_name="Bed 1 ID",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="bed2",
            field=models.CharField(
                blank=True,
                help_text="Bed 2 ID",
                max_length=20,
                null=True,
                verbose_name="Bed 2 ID",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="bed3",
            field=models.CharField(
                blank=True,
                help_text="Bed 3 ID",
                max_length=20,
                null=True,
                verbose_name="Bed 3 ID",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="bed4",
            field=models.CharField(
                blank=True,
                help_text="Bed 4 ID",
                max_length=20,
                null=True,
                verbose_name="Bed 4 ID",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(
                help_text="Room Number, e.g. 101, 102",
                max_length=20,
                unique=True,
                verbose_name="Room Number",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
