# Generated by Django 4.2.9 on 2026-01-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_options_remove_room_bed1_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
