# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("birthday", "生日提醒"),
                            ("festival", "节日关怀"),
                            ("health", "健康提醒"),
                            ("anniversary", "纪念日"),
                        ],
                        max_length=20,
                        verbose_name="提醒类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="提醒标题")),
                ("content", models.TextField(verbose_name="提醒内容")),
                ("reminder_date", models.DateField(verbose_name="提醒日期")),
                (
                    "is_participated",
                    models.BooleanField(default=False, verbose_name="是否参与"),
                ),
                (
                    "participation_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="参与方式"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "关怀提醒",
                "verbose_name_plural": "关怀提醒管理",
                "ordering": ["reminder_date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "系统通知"),
                            ("service", "服务通知"),
                            ("health", "健康通知"),
                            ("payment", "支付通知"),
                            ("appointment", "预约通知"),
                            ("task", "任务通知"),
                            ("birthday", "生日提醒"),
                            ("festival", "节日关怀"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "status",
                    models.CharField(
                        choices=[("unread", "未读"), ("read", "已读")],
                        default="unread",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "related_id",
                    models.IntegerField(blank=True, null=True, verbose_name="关联ID"),
                ),
                (
                    "related_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="关联类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReminderParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(max_length=20, verbose_name="参与方式"),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="留言内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "提醒参与记录",
                "verbose_name_plural": "提醒参与管理",
            },
        ),
    ]
