# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
        ("notifications", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderparticipation",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.familyuser",
                verbose_name="参与亲属",
            ),
        ),
        migrations.AddField(
            model_name="reminderparticipation",
            name="reminder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.carereminder",
                verbose_name="关怀提醒",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收用户",
            ),
        ),
        migrations.AddField(
            model_name="carereminder",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="院民",
            ),
        ),
    ]
