# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField(verbose_name="记录日期")),
                (
                    "record_time",
                    models.TimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "vital_signs",
                    models.JSONField(blank=True, null=True, verbose_name="生命体征"),
                ),
                ("diet", models.JSONField(blank=True, null=True, verbose_name="饮食情况")),
                ("sleep", models.JSONField(blank=True, null=True, verbose_name="睡眠情况")),
                (
                    "bowel_movement",
                    models.JSONField(blank=True, null=True, verbose_name="排便情况"),
                ),
                ("mental_state", models.CharField(max_length=255, verbose_name="精神状况")),
                (
                    "medications",
                    models.JSONField(blank=True, null=True, verbose_name="用药情况"),
                ),
                (
                    "care_activities",
                    models.JSONField(blank=True, null=True, verbose_name="护理活动"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "护理记录",
                "verbose_name_plural": "护理记录管理",
                "ordering": ["-record_date", "-record_time"],
            },
        ),
        migrations.CreateModel(
            name="CareTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                ("care_level", models.CharField(max_length=20, verbose_name="适用护理等级")),
                ("template_content", models.JSONField(verbose_name="模板内容")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "护理模板",
                "verbose_name_plural": "护理模板管理",
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "care_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="care_records.carerecord",
                        verbose_name="护理记录",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="体温",
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="心率"),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(blank=True, null=True, verbose_name="收缩压"),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True, verbose_name="舒张压"),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="呼吸频率"),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="血氧饱和度",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "生命体征",
                "verbose_name_plural": "生命体征管理",
            },
        ),
    ]
