# Generated by Django 4.2.9 on 2026-01-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0010_patient_primary_nurse_alter_healthassessment_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0010_alter_staffuser_department_alter_staffuser_position"),
        ("care_records", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carerecord",
            options={
                "ordering": ["-record_date", "-record_time"],
                "verbose_name": "Care Record",
                "verbose_name_plural": "Care Records",
            },
        ),
        migrations.AlterModelOptions(
            name="caretemplate",
            options={
                "verbose_name": "Care Template",
                "verbose_name_plural": "Care Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="vitalsigns",
            options={
                "verbose_name": "Vital Signs",
                "verbose_name_plural": "Vital Signs",
            },
        ),
        migrations.RemoveField(
            model_name="vitalsigns",
            name="blood_pressure_diastolic",
        ),
        migrations.RemoveField(
            model_name="vitalsigns",
            name="blood_pressure_systolic",
        ),
        migrations.RemoveField(
            model_name="vitalsigns",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="vitalsigns",
            name="oxygen_saturation",
        ),
        migrations.RemoveField(
            model_name="vitalsigns",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="vitalsigns",
            name="blood_oxygen",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Blood Oxygen"
            ),
        ),
        migrations.AddField(
            model_name="vitalsigns",
            name="diastolic_pressure",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Diastolic Pressure"
            ),
        ),
        migrations.AddField(
            model_name="vitalsigns",
            name="systolic_pressure",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Systolic Pressure"
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="bowel_movement",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Bowel Movement"
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="care_activities",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Care Activities"
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="diet",
            field=models.JSONField(blank=True, null=True, verbose_name="Diet"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="medications",
            field=models.JSONField(blank=True, null=True, verbose_name="Medications"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="mental_state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mental State"
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="record_date",
            field=models.DateField(verbose_name="Record Date"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="record_time",
            field=models.TimeField(auto_now_add=True, verbose_name="Record Time"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="sleep",
            field=models.JSONField(blank=True, null=True, verbose_name="Sleep"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="Staff",
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="vital_signs",
            field=models.JSONField(blank=True, null=True, verbose_name="Vital Signs"),
        ),
        migrations.AlterField(
            model_name="caretemplate",
            name="care_level",
            field=models.CharField(max_length=20, verbose_name="Care Level"),
        ),
        migrations.AlterField(
            model_name="caretemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="caretemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="caretemplate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="caretemplate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Template Name"),
        ),
        migrations.AlterField(
            model_name="caretemplate",
            name="template_content",
            field=models.JSONField(verbose_name="Template Content"),
        ),
        migrations.AlterField(
            model_name="caretemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="vitalsigns",
            name="care_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="care_records.carerecord",
                verbose_name="Care Record",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsigns",
            name="heart_rate",
            field=models.IntegerField(blank=True, null=True, verbose_name="Heart Rate"),
        ),
        migrations.AlterField(
            model_name="vitalsigns",
            name="respiratory_rate",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Respiratory Rate"
            ),
        ),
        migrations.AlterField(
            model_name="vitalsigns",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Temperature",
            ),
        ),
        migrations.CreateModel(
            name="DailyCareTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Task Date"
                    ),
                ),
                (
                    "vital_signs_normal",
                    models.BooleanField(
                        default=False, verbose_name="Vital Signs Normal"
                    ),
                ),
                (
                    "diet_normal",
                    models.BooleanField(default=False, verbose_name="Diet Normal"),
                ),
                (
                    "mental_normal",
                    models.BooleanField(
                        default=False, verbose_name="Mental State Normal"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.staffuser",
                        verbose_name="Last Updated By",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Care Task",
                "verbose_name_plural": "Daily Care Tasks",
                "ordering": ["patient__room"],
                "unique_together": {("patient", "task_date")},
            },
        ),
    ]
