# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255, verbose_name="服务名称")),
                ("description", models.TextField(verbose_name="服务描述")),
                ("expected_date", models.DateField(verbose_name="期望服务日期")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="服务费用"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="服务反馈"),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="评分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个性化服务申请",
                "verbose_name_plural": "个性化服务管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="服务名称")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("daily", "日常护理"),
                            ("medical", "医疗服务"),
                            ("recreation", "娱乐活动"),
                            ("custom", "个性化服务"),
                            ("consultation", "咨询服务"),
                        ],
                        max_length=20,
                        verbose_name="服务类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="服务描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="服务价格"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(blank=True, null=True, verbose_name="服务时长（分钟）"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "服务",
                "verbose_name_plural": "服务管理",
            },
        ),
        migrations.CreateModel(
            name="ServiceExecution",
            fields=[
                (
                    "custom_service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="services.customservicerequest",
                        verbose_name="个性化服务",
                    ),
                ),
                ("execution_date", models.DateField(verbose_name="执行日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="执行备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "服务执行记录",
                "verbose_name_plural": "服务执行管理",
            },
        ),
    ]
