# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
        ("patients", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customservicerequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AddField(
            model_name="customservicerequest",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.familyuser",
                verbose_name="申请人",
            ),
        ),
        migrations.AddField(
            model_name="customservicerequest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="院民",
            ),
        ),
        migrations.AddField(
            model_name="customservicerequest",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.service",
                verbose_name="服务类型",
            ),
        ),
        migrations.AddField(
            model_name="serviceexecution",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="服务人员",
            ),
        ),
    ]
