# Generated by Django 4.2.9 on 2026-01-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_id_registerapplication"),
        ("patients", "0010_patient_primary_nurse_alter_healthassessment_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Service Feedback",
                "verbose_name_plural": "Service Feedbacks",
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Order No"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rated", "Rated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.familyuser",
                        verbose_name="Family",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Order",
                "verbose_name_plural": "Service Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="customservicerequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Custom Service Request",
                "verbose_name_plural": "Custom Service Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="serviceexecution",
            options={
                "verbose_name": "Service Execution",
                "verbose_name_plural": "Service Executions",
            },
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="expected_date",
            field=models.DateField(verbose_name="Expected Date"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.familyuser",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="rating",
            field=models.IntegerField(blank=True, null=True, verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.service",
                verbose_name="Service Type",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="service_name",
            field=models.CharField(max_length=255, verbose_name="Service Name"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duration (min)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Service Name"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily Care"),
                    ("medical", "Medical Service"),
                    ("recreation", "Recreation"),
                    ("custom", "Personalized Service"),
                    ("consultation", "Consultation"),
                ],
                max_length=20,
                verbose_name="Service Type",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="custom_service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="services.customservicerequest",
                verbose_name="Custom Service",
            ),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="end_time",
            field=models.TimeField(verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="execution_date",
            field=models.DateField(verbose_name="Execution Date"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="Staff",
            ),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="start_time",
            field=models.TimeField(verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.CreateModel(
            name="ServiceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=5, verbose_name="Rating (1-5)")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="services.serviceorder",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Review",
                "verbose_name_plural": "Service Reviews",
            },
        ),
        migrations.CreateModel(
            name="ServiceOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        max_length=255, verbose_name="Service Name Snapshot"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price Snapshot"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="services.serviceorder",
                        verbose_name="Order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.CreateModel(
            name="ServiceFeedbackImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="service_feedback/", verbose_name="Image"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="services.servicefeedback",
                        verbose_name="Feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Image",
                "verbose_name_plural": "Feedback Images",
            },
        ),
        migrations.AddField(
            model_name="servicefeedback",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="services.serviceorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="servicefeedback",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.staffuser",
                verbose_name="Staff",
            ),
        ),
    ]
