# Generated by Django 4.2.9 on 2026-01-29 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0008_alter_user_id_registerapplication"),
        ("patients", "0010_patient_primary_nurse_alter_healthassessment_id_and_more"),
        ("services", "0003_servicefeedback_serviceorder_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customservicerequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "个性化服务申请",
                "verbose_name_plural": "个性化服务管理",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "服务", "verbose_name_plural": "服务管理"},
        ),
        migrations.AlterModelOptions(
            name="serviceexecution",
            options={"verbose_name": "服务执行记录", "verbose_name_plural": "服务执行管理"},
        ),
        migrations.AlterModelOptions(
            name="servicefeedback",
            options={"verbose_name": "服务反馈", "verbose_name_plural": "服务反馈"},
        ),
        migrations.AlterModelOptions(
            name="servicefeedbackimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="serviceorder",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "服务订单",
                "verbose_name_plural": "服务订单",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceorderitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="servicereview",
            options={"verbose_name": "服务评价", "verbose_name_plural": "服务评价"},
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.staffuser",
                verbose_name="服务人员",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderitem",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="服务费用"
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="description",
            field=models.TextField(verbose_name="服务描述"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="expected_date",
            field=models.DateField(verbose_name="期望服务日期"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.familyuser",
                verbose_name="申请人",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="服务反馈"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="院民",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="rating",
            field=models.IntegerField(blank=True, null=True, verbose_name="评分"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.service",
                verbose_name="服务类型",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="service_name",
            field=models.CharField(max_length=255, verbose_name="服务名称"),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("approved", "已批准"),
                    ("rejected", "已拒绝"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="customservicerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="服务描述"),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(blank=True, null=True, verbose_name="服务时长（分钟）"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, verbose_name="服务名称"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="服务价格"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("daily", "日常护理"),
                    ("medical", "医疗服务"),
                    ("recreation", "娱乐活动"),
                    ("custom", "个性化服务"),
                    ("consultation", "咨询服务"),
                ],
                max_length=20,
                verbose_name="服务类型",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="custom_service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="services.customservicerequest",
                verbose_name="个性化服务",
            ),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="end_time",
            field=models.TimeField(verbose_name="结束时间"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="execution_date",
            field=models.DateField(verbose_name="执行日期"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="执行备注"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="服务人员",
            ),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="start_time",
            field=models.TimeField(verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="serviceexecution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="servicefeedback",
            name="content",
            field=models.TextField(verbose_name="反馈内容"),
        ),
        migrations.AlterField(
            model_name="servicefeedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="servicefeedback",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="services.serviceorder",
                verbose_name="订单",
            ),
        ),
        migrations.AlterField(
            model_name="servicefeedback",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="服务人员",
            ),
        ),
        migrations.AlterField(
            model_name="servicefeedbackimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="servicefeedbackimage",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="services.servicefeedback",
            ),
        ),
        migrations.AlterField(
            model_name="servicefeedbackimage",
            name="image",
            field=models.ImageField(upload_to="feedback_images/", verbose_name="图片"),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.familyuser",
                verbose_name="亲属",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="order_no",
            field=models.CharField(max_length=50, unique=True, verbose_name="订单号"),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="服务对象",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Staff"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("rated", "Rated"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="总金额"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="serviceorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="services.serviceorder",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="单价"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderitem",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderitem",
            name="service_name",
            field=models.CharField(max_length=255, verbose_name="服务名称"),
        ),
        migrations.AlterField(
            model_name="servicereview",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="评价内容"),
        ),
        migrations.AlterField(
            model_name="servicereview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="servicereview",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="services.serviceorder",
                verbose_name="订单",
            ),
        ),
        migrations.AlterField(
            model_name="servicereview",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                verbose_name="评分",
            ),
        ),
    ]
