# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("nursing", "护理任务"),
                            ("admin", "管理任务"),
                            ("service", "服务任务"),
                            ("bed_scheduling", "床位调度"),
                            ("activity", "活动安排"),
                        ],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="任务标题")),
                ("description", models.TextField(verbose_name="任务描述")),
                ("due_date", models.DateField(verbose_name="截止日期")),
                (
                    "due_time",
                    models.TimeField(blank=True, null=True, verbose_name="截止时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "处理中"),
                            ("completed", "已完成"),
                            ("delayed", "已延迟"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务管理",
                "ordering": ["-due_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
            ],
            options={
                "verbose_name": "任务分配",
                "verbose_name_plural": "任务分配管理",
            },
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="tasks.task",
                        verbose_name="任务",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完成时间"),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, null=True, verbose_name="完成备注"),
                ),
                (
                    "attached_files",
                    models.JSONField(blank=True, null=True, verbose_name="附件"),
                ),
            ],
            options={
                "verbose_name": "任务完成记录",
                "verbose_name_plural": "任务完成管理",
            },
        ),
    ]
