# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
        ("patients", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="分配人",
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="分配人员",
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.task",
                verbose_name="任务",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.patient",
                verbose_name="关联院民",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="负责人",
            ),
        ),
        migrations.AddField(
            model_name="taskcompletion",
            name="completed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="完成人",
            ),
        ),
    ]
