# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=50, verbose_name="房间号")),
                ("bed_id", models.CharField(max_length=20, verbose_name="床位号")),
                ("building", models.CharField(max_length=20, verbose_name="楼栋")),
                ("floor", models.IntegerField(verbose_name="楼层")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("occupied", "已占用"),
                            ("cleaning", "清洁中"),
                            ("maintenance", "维修中"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "床位",
                "verbose_name_plural": "床位管理",
                "ordering": ["building", "floor", "room_number", "bed_id"],
            },
        ),
        migrations.CreateModel(
            name="BedAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assign_date", models.DateField(verbose_name="分配日期")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "已分配"),
                            ("active", "使用中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "床位分配",
                "verbose_name_plural": "床位分配管理",
                "ordering": ["-assign_date"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=50, unique=True, verbose_name="房间号"),
                ),
                ("building", models.CharField(max_length=20, verbose_name="楼栋")),
                ("floor", models.IntegerField(verbose_name="楼层")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "单人房"),
                            ("double", "双人房"),
                            ("triple", "三人房"),
                            ("suite", "套房"),
                        ],
                        max_length=20,
                        verbose_name="房间类型",
                    ),
                ),
                ("max_capacity", models.IntegerField(verbose_name="最大容量")),
                (
                    "current_occupancy",
                    models.IntegerField(default=0, verbose_name="当前入住人数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间管理",
                "ordering": ["building", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="CleaningRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(auto_now_add=True, verbose_name="请求日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "处理中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bed_scheduling.bed",
                        verbose_name="床位",
                    ),
                ),
            ],
            options={
                "verbose_name": "保洁请求",
                "verbose_name_plural": "保洁管理",
                "ordering": ["-requested_date"],
            },
        ),
    ]
