# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bed_scheduling", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaningrequest",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleaning_requests_completed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="完成人",
            ),
        ),
        migrations.AddField(
            model_name="cleaningrequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleaning_requests_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="请求人",
            ),
        ),
        migrations.AddField(
            model_name="cleaningrequest",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bed_scheduling.room",
                verbose_name="房间",
            ),
        ),
        migrations.AddField(
            model_name="bedassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="分配人",
            ),
        ),
        migrations.AddField(
            model_name="bedassignment",
            name="bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bed_scheduling.bed",
                verbose_name="床位",
            ),
        ),
        migrations.AddField(
            model_name="bedassignment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="院民",
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.patient",
                verbose_name="当前院民",
            ),
        ),
    ]
