# Generated by Django 4.2.9 on 2026-01-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_add_room_field"),
        ("bed_scheduling", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bed",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bed",
                to="patients.patient",
                verbose_name="当前院民",
            ),
        ),
    ]
