# Generated by Django 4.2.9 on 2026-01-21 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bed_scheduling", "0003_alter_bed_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bedassignment",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="bedassignment",
            name="bed",
        ),
        migrations.RemoveField(
            model_name="bedassignment",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="cleaningrequest",
            name="bed",
        ),
        migrations.RemoveField(
            model_name="cleaningrequest",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="cleaningrequest",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="cleaningrequest",
            name="room",
        ),
        migrations.DeleteModel(
            name="Bed",
        ),
        migrations.DeleteModel(
            name="BedAssignment",
        ),
        migrations.DeleteModel(
            name="CleaningRequest",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
