# Generated by Django 4.2.9 on 2026-02-05 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0010_patient_primary_nurse_alter_healthassessment_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0003_alter_room_created_at_alter_room_updated_at"),
        ("bed_scheduling", "0004_remove_bedassignment_assigned_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(max_length=10, verbose_name="Bed Number"),
                ),
                ("assign_date", models.DateTimeField(verbose_name="Assign Date")),
                (
                    "release_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cleaning_notified",
                    models.BooleanField(
                        default=False, verbose_name="Cleaning Notified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "elderly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Elderly",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed Assignment",
                "verbose_name_plural": "Bed Assignments",
                "ordering": ["-created_at"],
            },
        ),
    ]
