# Generated by Django 4.2.9 on 2025-12-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(auto_now_add=True, verbose_name="评估日期"),
                ),
                ("health_level", models.CharField(max_length=20, verbose_name="健康等级")),
                ("vital_signs", models.JSONField(verbose_name="生命体征")),
                ("chronic_diseases", models.JSONField(verbose_name="慢性病")),
                ("allergies", models.JSONField(verbose_name="过敏史")),
                ("assessment_summary", models.TextField(verbose_name="评估总结")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "健康评估",
                "verbose_name_plural": "健康评估管理",
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(auto_now_add=True, verbose_name="记录日期"),
                ),
                ("diagnosis", models.TextField(verbose_name="诊断结果")),
                ("treatment", models.TextField(verbose_name="治疗方案")),
                ("medications", models.JSONField(verbose_name="用药记录")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "医疗记录",
                "verbose_name_plural": "医疗记录管理",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "id_card",
                    models.CharField(max_length=18, unique=True, verbose_name="身份证号"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地址"
                    ),
                ),
                ("care_level", models.CharField(max_length=20, verbose_name="护理等级")),
                (
                    "bed_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="床位号"
                    ),
                ),
                ("admission_date", models.DateField(verbose_name="入院日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "在院"),
                            ("discharged", "已出院"),
                            ("transferred", "已转院"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "院民",
                "verbose_name_plural": "院民管理",
            },
        ),
    ]
