# Generated by Django 4.2.9 on 2026-01-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patient_id_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="health_level",
            field=models.CharField(default="good", max_length=20, verbose_name="健康等级"),
        ),
    ]
