# Generated by Django 4.2.9 on 2026-01-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
        ("patients", "0004_patient_health_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="rooms.room",
                verbose_name="房间号",
            ),
        ),
    ]
