# Generated by Django 4.2.9 on 2026-01-16 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bed_scheduling", "0003_alter_bed_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0003_alter_room_created_at_alter_room_updated_at"),
        ("patients", "0005_add_room_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthassessment",
            options={
                "ordering": ["-assessment_date"],
                "verbose_name": "健康评估",
                "verbose_name_plural": "健康评估管理",
            },
        ),
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={
                "ordering": ["-record_date"],
                "verbose_name": "医疗记录",
                "verbose_name_plural": "医疗记录管理",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, null=True, verbose_name="过敏史"),
        ),
        migrations.AddField(
            model_name="patient",
            name="bed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_patient",
                to="bed_scheduling.bed",
                verbose_name="床位",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="血型"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="紧急联系人"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="紧急联系电话"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, null=True, verbose_name="病史"),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="allergies",
            field=models.TextField(blank=True, null=True, verbose_name="过敏史"),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="assessment_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="评估日期"),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="assessment_summary",
            field=models.TextField(blank=True, null=True, verbose_name="评估总结"),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="chronic_diseases",
            field=models.TextField(blank=True, null=True, verbose_name="慢性疾病"),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="vital_signs",
            field=models.TextField(blank=True, null=True, verbose_name="生命体征"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="diagnosis",
            field=models.TextField(verbose_name="诊断"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="medications",
            field=models.TextField(blank=True, null=True, verbose_name="用药情况"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="record_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="记录日期"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="treatment",
            field=models.TextField(blank=True, null=True, verbose_name="治疗方案"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateField(blank=True, null=True, verbose_name="入院日期"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="bed_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="床位号"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="care_level",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="护理等级"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="health_level",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="健康等级"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rooms.room",
                verbose_name="房间",
            ),
        ),
        migrations.CreateModel(
            name="PatientHealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_type", models.CharField(max_length=100, verbose_name="记录类型")),
                ("content", models.TextField(verbose_name="记录内容")),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="院民",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="记录人",
                    ),
                ),
            ],
            options={
                "verbose_name": "院民健康记录",
                "verbose_name_plural": "院民健康记录管理",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "身份证"),
                            ("medical_certificate", "体检证明"),
                            ("insurance", "保险单"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="档案类型",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_url", models.URLField(verbose_name="文件URL")),
                ("file_size", models.IntegerField(verbose_name="文件大小（字节）")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="院民",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "院民档案",
                "verbose_name_plural": "院民档案管理",
            },
        ),
    ]
