# Generated by Django 4.2.9 on 2026-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_alter_healthassessment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="bed",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="room",
        ),
        migrations.AddField(
            model_name="patient",
            name="room_id",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="房间号"
            ),
        ),
    ]
