# Generated by Django 4.2.9 on 2026-01-20 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_remove_patient_bed_remove_patient_room_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="room_id",
            new_name="room",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="bed_id",
        ),
    ]
