# Generated by Django 4.2.9 on 2026-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0008_rename_room_id_patient_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="bed_id",
            field=models.CharField(
                blank=True, max_length=1, null=True, verbose_name="床位号"
            ),
        ),
    ]
