# Generated by Django 4.2.9 on 2026-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_leaverequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男"), ("female", "女")],
                max_length=10,
                null=True,
                verbose_name="性别",
            ),
        ),
    ]
