# Generated by Django 4.2.9 on 2026-01-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_staffuser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffuser",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
