# Generated by Django 4.2.9 on 2026-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_staffuser_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyuser",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="账户余额"
            ),
        ),
    ]
