# Generated by Django 4.2.9 on 2026-01-29 08:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0010_patient_primary_nurse_alter_healthassessment_id_and_more"),
        ("users", "0008_alter_user_id_registerapplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familyuser",
            options={
                "verbose_name": "Family User",
                "verbose_name_plural": "Family Users",
            },
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="registerapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Registration Application",
                "verbose_name_plural": "Registration Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="staffuser",
            options={
                "verbose_name": "Staff User",
                "verbose_name_plural": "Staff Users",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="proof_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="family_proofs/",
                verbose_name="Proof File",
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="relationship",
            field=models.CharField(max_length=50, verbose_name="Relationship"),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.staffuser",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("casual", "Casual Leave"),
                    ("annual", "Annual Leave"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Leave Type",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="patient_id_card",
            field=models.CharField(max_length=18, verbose_name="Patient ID Card"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="real_name",
            field=models.CharField(max_length=100, verbose_name="Real Name"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Rejection Reason"
            ),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="relationship",
            field=models.CharField(max_length=50, verbose_name="Relationship"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="registerapplication",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="department",
            field=models.CharField(max_length=100, verbose_name="Department"),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="position",
            field=models.CharField(max_length=100, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Joined"),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Department"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Is Superuser"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="patient_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Patient ID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=11, unique=True, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name",
            field=models.CharField(max_length=100, verbose_name="Real Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Relationship"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("staff", "Staff"), ("family", "Family")],
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Username"
            ),
        ),
    ]
