# Generated by Django 4.2.9 on 2026-01-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_familyuser_options_alter_leaverequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuser",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Department"
            ),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Position"
            ),
        ),
    ]
