# Generated by Django 4.2.9 on 2026-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_staffuser_department_alter_staffuser_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Rejection Reason"
            ),
        ),
    ]
