# Generated by Django 4.2.9 on 2026-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_leaverequest_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="Phone"),
        ),
    ]
